jobeet_affiliate:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetAffiliate
    module:               affiliate
    prefix_path:          /affiliate
    column:               id
    with_wildcard_routes: true



jobeet_category:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetCategory
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true



jobeet_job:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetJob
    module:               job
    prefix_path:          /job
    column:               id
    with_wildcard_routes: true



sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }



sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }



sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: job, action: index }



