affiliate:
  class: sfDoctrineRouteCollection
  options:
    model:          JobeetAffiliate
    actions:        [new, create]
    object_actions: { wait: get }
    prefix_path:    /:sf_culture/affiliate
  requirements:
    sf_culture: (?:ru|en)

category:
  url:     /:sf_culture/category/:slug.:sf_format
  class:   sfDoctrineRoute
  param:   { module: category, action: show, sf_format: html }
  options: { model: JobeetCategory, type: object, method: doSelectForSlug }
  requirements:
    sf_format: (?:html|atom)
    sf_culture: (?:ru|en)

job_search:
  url:   /:sf_culture/search
  param: { module: job, action: search }
  requirements:
    sf_culture: (?:ru|en)

job:
  class: sfDoctrineRouteCollection
  options:
    model:          JobeetJob
    column:         token
    object_actions: { publish: put, extend: put }
    prefix_path:    /:sf_culture/job
  requirements:
    token: \w+
    sf_culture: (?:ru|en)

job_show_user:
  url:     /:sf_culture/job/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: JobeetJob
    type: object
    method_for_query: retrieveActiveJob
  param:   { module: job, action: show }
  requirements:
    id:        \d+
    sf_method: get
    sf_culture: (?:ru|en)

api_jobs:
  url:     /api/:token/:num/jobs.:sf_format/:cat
  class:   sfDoctrineRoute
  param:   { module: api, action: list }
  options: { model: JobeetJob, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)
    num: \d+
    sf_culture: (?:ru|en)

api:
  url: /:sf_culture/api
  params: {module: api, action: api}
  requirements:
    sf_culture: (?:ru|en)

localized_homepage:
  url:   /:sf_culture/
  param: { module: job, action: index }
  requirements:
    sf_culture: (?:ru|en)

change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }

# default rules
homepage:
  url:   /
  param: { module: job, action: index }

#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*